---
title: "Sharktank - Rafael"
output: html_document
date: "2023-03-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
library(naniar)
library(RColorBrewer)
```

Load data in

```{r}
sharktank <-readr::read_csv("Our data/Shark Tank US dataset.csv")
```

Take a look

```{r}
glimpse(sharktank)
```

clean the names

```{r}
sharktank <- clean_names(sharktank)
names(sharktank)
```

Separate the `business_description` column
```{r}
sharktank <- sharktank %>% 
  separate(business_description, into= c("business_name", "business_description"), sep = " - ")
#gives error because some businesses do not have a description
```

Removing dashes from ends of business names
```{r}
sharktank$business_name <- gsub("-$", "", sharktank$business_name)
```


# Looking at trends across seasons

How many products each season?
```{r}
sharktank %>% 
  count(season_number)
```
Find the most popular type of product for each season and make it a bar graph


